
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#别名的配置
mybatis:
  type-aliases-package: cn.itsource.spring.domain,cn.itsource.spring.query
server:
  port: 80
